## Practice:

**Дано дві таблиці: перша з інформацією про клієнтів ("_ID_", "_Ім'я_", "_Місто_"), друга — з їхніми замовленнями ("_ID клієнта_", "_Замовлення_", "_Вартість_").**

-   Створіть два DataFrame і заповніть їх не менш ніж п'ятьма рядками кожен.
-   Виведіть обидва DataFrame.
-   Об'єднайте їх за ідентифікатором клієнта.
-   Підрахуйте загальну вартість замовлень за кожним клієнтом.
-   Виведіть результат у вигляді нового DataFrame.

In [1]:
import pandas as pd

customers = {
    "ID": [1, 2, 3, 4, 5],
    "Ім'я": ["Іван", "Олена", "Петро", "Марія", "Андрій"],
    "Місто": ["Київ", "Львів", "Одеса", "Київ", "Харків"]
}

orders = {
    "ID клієнта": [1, 1, 2, 3, 4, 5],
    "Замовлення": ["Ноутбук", "Мишка", "Клавіатура", "Монітор", "Навушники", "Камера"],
    "Вартість": [25000, 800, 1500, 7000, 2000, 12000]
}

df_customers = pd.DataFrame(customers)
df_orders = pd.DataFrame(orders)

print(df_customers)
print('-------------------------------------------')
print(df_orders)

   ID    Ім'я   Місто
0   1    Іван    Київ
1   2   Олена   Львів
2   3   Петро   Одеса
3   4   Марія    Київ
4   5  Андрій  Харків
-------------------------------------------
   ID клієнта  Замовлення  Вартість
0           1     Ноутбук     25000
1           1       Мишка       800
2           2  Клавіатура      1500
3           3     Монітор      7000
4           4   Навушники      2000
5           5      Камера     12000

In [2]:
merged_df = pd.merge(df_customers, df_orders, left_on="ID", right_on="ID клієнта")
merged_df

   ID    Ім'я   Місто  ID клієнта  Замовлення  Вартість
0   1    Іван    Київ           1     Ноутбук     25000
1   1    Іван    Київ           1       Мишка       800
2   2   Олена   Львів           2  Клавіатура      1500
3   3   Петро   Одеса           3     Монітор      7000
4   4   Марія    Київ           4   Навушники      2000
5   5  Андрій  Харків           5      Камера     12000

In [3]:
print('Загальна вартість замовлень за кожним клієнтом:')
merged_df.groupby("Ім'я")["Вартість"].sum().reset_index()

Загальна вартість замовлень за кожним клієнтом:

     Ім'я  Вартість
0    Іван     25800
1  Андрій     12000
2   Марія      2000
3   Олена      1500
4   Петро      7000