## Practice

**Завдання 6:**
Зібрано дані про товари та продажі у двох таблицях. Перша містить: "_ID_", "_Назва_", "_Ціна_". Друга містить: "_ID_", "_Кількість_".

-   Створіть два DataFrame і заповніть їх не менш ніж п'ятьма рядками.
-   Виведіть обидва DataFrame.
-   Об'єднайте їх за колонкою "_ID_".
-   Додайте новий стовпець "_Сума_" як добуток ціни та кількості.
-   Виведіть підсумковий DataFrame.

In [10]:
import pandas as pd

In [11]:
products = {
    "ID": [1, 2, 3, 4, 5],
    "Назва": ["Ноутбук", "Мишка", "Клавіатура", "Монітор", "Навушники"],
    "Ціна": [25000, 350, 800, 7500, 1200]
}

sales = {
    "ID": [1, 2, 3, 4, 5],
    "Кількість": [3, 15, 10, 5, 8]
}

df_products = pd.DataFrame(products)
df_products

   ID       Назва   Ціна
0   1     Ноутбук  25000
1   2       Мишка    350
2   3  Клавіатура    800
3   4     Монітор   7500
4   5   Навушники   1200

In [12]:
df_sales = pd.DataFrame(sales)
df_sales

   ID  Кількість
0   1          3
1   2         15
2   3         10
3   4          5
4   5          8

In [13]:
df = df_products.merge(df_sales, on='ID', how='inner')
df

   ID       Назва   Ціна  Кількість
0   1     Ноутбук  25000          3
1   2       Мишка    350         15
2   3  Клавіатура    800         10
3   4     Монітор   7500          5
4   5   Навушники   1200          8

In [14]:
df['Сума'] = df['Ціна'].multiply(df['Кількість'])
df

   ID       Назва   Ціна  Кількість   Сума
0   1     Ноутбук  25000          3  75000
1   2       Мишка    350         15   5250
2   3  Клавіатура    800         10   8000
3   4     Монітор   7500          5  37500
4   5   Навушники   1200          8   9600