## Practice:
**Завдання 6:**
Зібрано дані про товари та продажі у двох таблицях. Перша містить: "_ID_", "_Назва_", "_Ціна_". Друга містить: "_ID_", "_Кількість_".

-   Створіть два DataFrame і заповніть їх не менш ніж п'ятьма рядками.
-   Виведіть обидва DataFrame.
-   Об'єднайте їх за колонкою "_ID_".
-   Додайте новий стовпець "_Сума_" як добуток ціни та кількості.
-   Виведіть підсумковий DataFrame.

In [1]:
import pandas as pd

products = {
    "ID": [1, 2, 3, 4, 5],
    "Назва": ["Ноутбук", "Мишка", "Клавіатура", "Монітор", "Телефон"],
    "Ціна": [25000, 800, 1500, 7000, 18000]
}

sales = {
    "ID": [1, 2, 3, 4, 5],
    "Кількість": [5, 30, 20, 8, 12]
}

df_products = pd.DataFrame(products)
df_products

   ID       Назва   Ціна
0   1     Ноутбук  25000
1   2       Мишка    800
2   3  Клавіатура   1500
3   4     Монітор   7000
4   5     Телефон  18000

In [2]:
df_sales = pd.DataFrame(sales)
df_sales

   ID  Кількість
0   1          5
1   2         30
2   3         20
3   4          8
4   5         12

In [3]:
df = df_products.merge(df_sales, on='ID', how='inner')
df

   ID       Назва   Ціна  Кількість
0   1     Ноутбук  25000          5
1   2       Мишка    800         30
2   3  Клавіатура   1500         20
3   4     Монітор   7000          8
4   5     Телефон  18000         12

In [4]:
df['Сума'] = df['Ціна'].multiply(df['Кількість'])
df

   ID       Назва   Ціна  Кількість    Сума
0   1     Ноутбук  25000          5  125000
1   2       Мишка    800         30   24000
2   3  Клавіатура   1500         20   30000
3   4     Монітор   7000          8   56000
4   5     Телефон  18000         12  216000